name = "MultiBisect"
uuid = "66877b0d-840f-4af8-a0b5-b62f5ea465b3"
authors = ["Jack Shannon <j.b.shannon@lse.ac.uk> and contributors"]
version = "1.0.0-DEV"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[compat]
julia = "1.6"
Logging = "1.6"
Roots = "2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
