name = "MultiBisect"
uuid = "66877b0d-840f-4af8-a0b5-b62f5ea465b3"
authors = ["Jack Shannon <j.b.shannon@lse.ac.uk> and contributors"]
version = "0.2.1"

[deps]
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[compat]
julia = "1.10"
Roots = "2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
